### PR TITLE
Added initial maui toolkit template

### PR DESCRIPTION
**Pull request by bijington**
An initial attempt at creating a template that can be used by contributors

### CODE REVIEW

**Comment by PRMerger15** [comment]
@bijington : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by bijington** [comment]
@davidbritch I have tried to follow the same convention as: https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/main/docs/.template.md from the Xamarin Community Toolkit docs repo. I wanted to check if this file naming convention allows the file to be ignored by the docs generation process or if there is any extra config we need?

**Comment by bijington** [comment]
- [ ] Add Banner for 'preview' information

**Comment by PRMerger13** [comment]
@bijington : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by davidbritch** [comment]
Correct - .template.md gets ignored by the build process.

**Review by brminnick — APPROVED** [review]

**Comment by PRMerger18** [comment]
@bijington : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger15** [comment]
@bijington : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by michael-hawker** [comment]
FYI here's the existing template we use: https://raw.githubusercontent.com/MicrosoftDocs/WindowsCommunityToolkitDocs/main/docs/.template.md

We find the platform API section at the top is useful to align to how the guidance docs usually summarize links to API docs.

**Comment by davidbritch** [comment]
Re: 

If any API docs are produced using mdoc, which is the .NET standard for producing API docs, API doc links should use xref syntax: e.g. [`Page`](xref:Xamarin.Forms.Page). This syntax provides build time validation of API doc links, unlike the /dotnet/api format.

**Comment by PRMerger16** [comment]
@bijington : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Pull request merged**
