### PR TITLE
Initial MaxLengthReachedBehavior page

### PR DESCRIPTION
**Pull request by bijington**
Documentation added for .NET MAUI Community Toolkit proposals:

- `[Proposal] Maximum Length Reached Behavior` <https://github.com/CommunityToolkit/Maui/issues/47>

### CODE REVIEW

**Comment by PRMerger15** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by bijington** [comment]
Currently this page is slightly different to the XCT docs at: https://docs.microsoft.com/en-gb/xamarin/community-toolkit/behaviors/maxlengthreachedbehavior

I can't quite work out how best to provide the varying details such as the extra properties and events. Perhaps I should follow the original approach?

**Comment by brminnick** [comment]
Yea, I think it's a good idea to post the Properties, Events, Methods, etc. in their own section. 

This allows us to highlight the features without requiring that we include them in the example.

**Comment by bijington** [comment]
> Yea, I think it's a good idea to post the Properties, Events, Methods, etc. in their own section. 
> 
> This allows us to highlight the features without requiring that we include them in the example. 

Do you think it would be a good idea to include the methods for converters also? That way we could explain the use of each parameter.

**Comment by brminnick** [comment]
> Do you think it would be a good idea to include the methods for converters also? 

Yea, I think that is best. Especially since certain Converters have specific uses for `parameter`.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by bijington** [comment]
> Screen Shot 2022-03-09 at 9 57 07 AM
> 
> Looking good! Is this ready for review?

Yes I believe so. There is only the topic of the format of the Properties and Events sections. I'm ok with sticking to the existing format though

**Review by brminnick — APPROVED** [review]

**Pull request merged**
