### PR TITLE
Add sample images

### PR DESCRIPTION
**Pull request by JoonghyunCho**
This PR adds screenshots of the sample code.

It currently includes Alerts, most of Behaviors, and DrawingView.
Alerts include the both Android and iOS images and others only have Android images.

### CODE REVIEW

**Comment by JoonghyunCho** [comment]
Tried to see how it looks :)

**Comment by jfversluis** [comment]
Thanks for this! I see there are a few warnings here that we want to fix: https://buildapi.docs.microsoft.com/Output/PullRequest/42ce6443-b3af-1e1b-1f87-f62bfbd983d2/202211221508556519-173/BuildReport?accessString=4b33093f23e093d2b65997712e2b35e1c9089cd85141b20019021d1be62f3d0f

Unfortunately as someone not working at Microsoft you can't see the preview, but here is a screenshot of one of the pages

image

**Comment by JoonghyunCho** [comment]
Oops.. my mistake for the warnings 😭  Just fixed all the warnings.
@jfversluis  Thanks for sharing the preview! looks ok to me!

**Review by bijington — APPROVED** [review]
Looks good to me! Thanks @JoonghyunCho

**Pull request merged**
