### PR TITLE
a small oversight in the setup section

### PR DESCRIPTION
**Pull request by HugoVG**
I was reading the document only to realise a lot of things broke just to find out you also had to append  ``.UseMauiCommunityToolkit()``.
i added it into the document so other people might not stumble over this

### CODE REVIEW

**Comment by PRMerger14** [comment]
@HugoVG : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jfversluis** [comment]
Hey @HugoVG! That is definitely useful, thanks!

You should however also be notified through code now though, we added an analyzer that will tell you that you didn't add this line yet: https://github.com/CommunityToolkit/Maui/pull/486#issuecomment-1184970979 

No need to read those pesky docs ;)

**Comment by HugoVG** [comment]
First off, love your videos. Just now I tried dotnet Maui and run into issues in the .gs looking at the docs I was a little confused, so I want to the main community toolkit docs and saw that there it was added, just wanted to add it here so other people shouldn't have to struggle

**Comment by bijington** [comment]
Excellent spot @HugoVG i can't believe we missed this.

I think we will want to move this change out to the individual package details below as the markup toolkit has its own Use method too.

**Comment by PRMerger8** [comment]
@jfversluis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bijington** [comment]
I'm on my phone right now but happy to provide a suggestion later

**Comment by jfversluis** [comment]
> First off, love your videos. Just now I tried dotnet Maui and run into issues in the .gs looking at the docs I was a little confused, so I want to the main community toolkit docs and saw that there it was added, just wanted to add it here so other people shouldn't have to struggle

Don't get me wrong, we should absolutely also describe this here ;)

**Comment by jfversluis** [comment]
@bijington yeah we might want to rethink the structuring here a bit altogether. Now the top part basically only describes the Toolkit alone as well and not Markup. On the other hand, people will probably just scan this to see what is needed to get started and we might not want to break it up too much.

Maybe in this same piece just add the init line for markup as well with a little line that you only need to use the one from the package that you actually need. That can be one of both or both.

**Comment by bijington** [comment]
@HugoVG thank you for submitting this, sorry it took me a while to add to it but I think it is a good improvement.

@jfversluis are you ok to take a look and see what you think?

**Review by bijington — APPROVED** [review]

**Comment by bijington** [comment]
@jfversluis this should be good to merge if you can work your magic please :)

**Comment by jfversluis** [comment]
@HugoVG seems like in order to accept this you will need to sign the CLA, did you do that yet?

**Comment by HugoVG** [comment]
> @HugoVG seems like in order to accept this you will need to sign the CLA, did you do that yet?

Should be done now

**Comment by jfversluis** [comment]
Perfect, thanks! Now I see merge conflicts 😅 But I'll handle those and merge this right after. Thanks Hugo!

**Pull request merged**
