### PR TITLE
Add `ItemsView` for `Maui.Markup`

### PR DESCRIPTION
**Pull request by brminnick**
This PR adds the `ItemsView` Extensions docs for `CommunityToolkit.Maui.Markup`

### CODE REVIEW

**Comment by PRMerger-2** [comment]
Microsoft authors of articles need to make updates through the private repository, so the updates can be staged and validated by current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged. 

It's easy to access the private repo version of your articles in GitHub. Just add *-pr* to the URL, as follows: 

 &nbsp;Public repo URL: `https://github.com/MicrosoftDocs/{docs-repo}` 
 &nbsp;Private repo URL: `https://github.com/MicrosoftDocs/{docs-repo-pr}` 

 We have closed this pull request. Please resubmit the updates through the private repo. For more information, see the [contributor guide](https://docs.microsoft.com/contribute/).

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Review by bijington — APPROVED** [review]
Looks good to me! Thanks @brminnick

**Comment by bijington** [comment]
Oh actually we should add this file also in to the `markup.md` table at the bottom.

**Review by jfversluis — CHANGES_REQUESTED** [review]
Content looks good, Shaun mentioned something about including it in the `markup.md` file as well? There is a table at the bottom there that seems to list these things.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Review by jfversluis — APPROVED** [review]

**Comment by brminnick** [comment]
> Oh actually we should add this file also in to the `markup.md` table at the bottom.

Done! ✅ 

I added in the other missing links to the table in `markup.md` too

**Pull request merged**
