### PR TITLE
Landing pages plus initial .NET MAUI docs (Branch)

### PR DESCRIPTION
**Pull request by brminnick**
This PR branches from #5 to see if the landing page problems persist.

This PR currently includes:
- Landing page for all 3 Community Toolkits
- .NET MAUI Community Toolkit introduction, getting started and table of contents

### CODE REVIEW

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Commits Count | This PR contains more than 15 commits.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Image File | This PR contains an image file(s).
 Index File | This PR contains a change to the index file.

**Comment by brminnick** [comment]
Screen Shot 2022-02-11 at 12 11 58 PM
Success!

**Comment by bijington** [comment]
Awesome thanks @brminnick

**Comment by michael-hawker** [comment]
@brminnick @bijington Hmm... I don't see the landing page on the staging review site for main... does it need to be rebuilt in the OPS portal? 

image

**Comment by bijington** [comment]
This is definitely outside of my limited knowledge but @davidbritch will probably know though

**Comment by bijington** [comment]
Is the CI step running against main or only on the PRs?

**Comment by davidbritch** [comment]
The build runs against every branch.

This issue has been puzzling me but I finally think I've found the source of the problem. The setting in OPS about where the docs source lives is wrong. But it's not editable because the value is picked up from the repo config. Except that in this case it isn't being picked up from the repo config. I'll have to prod docs support about it.

**Pull request merged**
