### PR TITLE
Improve the getting started experience

### LINKED ISSUE #200: Missing using(s) that are needed.
In the builder.*** it fails as it needs the using CommunityToolkit.Maui;

This is not in the docs.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Version Independent ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Content: [Getting Started with the .NET Multi-platform App UI (.NET MAUI) Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started)
* Content Source: [docs/maui/get-started.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

### LINKED ISSUE #218: Document doesn't specify what xmlns: to use to reference the Maui Community Toolkit
This document is missing a key piece of information to help the beginner use the Maui Community Toolkit.

In, say, a ContentPage, to reference, say, a MediaElement, there should be, in the <ContentPage...> element, a specification for the xmlns: value for the toolkit. This is not specified anywhere in the document.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Version Independent ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Content: [Getting Started with the .NET Multi-platform App UI (.NET MAUI) Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started)
* Content Source: [docs/maui/get-started.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

### PR DESCRIPTION
**Pull request by bijington**
- Fixes #200
- Fixes #218

Also includes a link to MediaElement and makes use of tabs for each package

### CODE REVIEW

**Comment by bijington** [comment]
@jfversluis any chance you could supply a preview of what the tabbed based approach looks like please?

**Comment by jfversluis** [comment]
I think something might be up... 
image

**Comment by bijington** [comment]
> I think something might be up... 
> 
> image
> 
> 

Perhaps it doesn't like the back ticks in the header. I'll try removing those in the morning 👍

Thanks

**Comment by bijington** [comment]
Sorry this PR grew!

**Comment by jfversluis** [comment]
Still no go on the tabs though :(

**Comment by bijington** [comment]
> Still no go on the tabs though :(

How about now?

**Comment by jfversluis** [comment]
I think so! Just that bulleted list looks a bit weird and doesn't seem to do anything? Under "Adding the NuGet package(s)" and then number 3. Those a, b, c options.

image

**Comment by bijington** [comment]
OK thanks, I can shift the tabs up to where that list is and then remove it 👍

**Comment by bijington** [comment]
Hopefully that is better

**Comment by bijington** [comment]
Although I am not sure we really need the numbers

**Comment by jfversluis** [comment]
I think this looks OK!

image

Some other warnings popped up though... 

* docs/maui/layouts/StateContainer.md
  * Line 3: [Warning] Invalid value for author: 'nicjay, brminnick' is not a valid GitHub ID.
  * Line 62: [Suggestion] Absolute link 'https://learn.microsoft.com/dotnet/communitytoolkit/maui/markup/markup' will be broken in isolated environments. Replace with a relative link.
  * Line 123: [Suggestion] Absolute link 'https://learn.microsoft.com/windows/communitytoolkit/mvvm/introduction' will be broken in isolated environments. Replace with a relative link.
* docs/maui/markup/markup.md
  * Line 20: [Warning] Cannot find bookmark '#communitytoolkitmauimarkup' in 'maui/get-started.md'.

**Comment by bijington** [comment]
Thanks no can't tell if this 2 steps forward and 1 back or vice-versa but we are getting there. I'll have a look at those warnings in a bit.

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
