### PR TITLE
IsListNullOrEmptyConverter documentation

### PR DESCRIPTION
**Pull request by bijington**
Documentation added for .NET MAUI Community Toolkit - `[Proposal] ListIsNullOrEmpty Converters` <https://github.com/CommunityToolkit/Maui/issues/69>

### CODE REVIEW

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by brminnick** [comment]
Screen Shot 2022-02-11 at 2 07 56 PM
Let's make sure to update the TOC to include this doc too.

Maybe something like this?
```
|    Setup
└─── Converters
|    └─── IsListNullOrEmptyConverter

**Comment by bijington** [comment]
> Screen Shot 2022-02-11 at 2 07 56 PM
> 
> Let's make sure to update the TOC to include this doc too.
> Maybe something like this?
> 
> ```
> └─── Setup
> └─── Converters
> |    └─── IsListNullOrEmptyConverter
> ```

Good catch thanks!

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by brminnick** [comment]
Thanks Shaun! Let's make sure to include C# Examples as well for folks like me who prefer C# over XAML 😊 

I think it's best to recommend `CommunityToolkit.Maui.Markup` and include it in the C# sample since `Maui.Markup` makes using Converters much easier, and it will also help raise awareness for the  [`CommunityToolkit.Maui.Markup` NuGet Package](https://www.nuget.org/packages/CommunityToolkit.Maui.Markup/).

Here's an example using the sample from the [Proposal](https://github.com/CommunityToolkit/Maui/issues/69):

## Syntax

### XAML
// XAML example

### C#

> Note: This C# Syntax leverages the [`CommunityToolkit.Maui.Markup` NuGet Package](https://www.nuget.org/packages/CommunityToolkit.Maui.Markup/)

```cs
using CommunityToolkit.Maui.Markup;

class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new Label().Bind(Label.IsVisible, nameof(ViewMode.MyList), converter: new IsListNullOrEmptyConverter();
  }
}
```

**Comment by brminnick** [comment]
> On the topic of Markup, I assume it should have its own folder and contents in the docs/TOC? Then once that is there this reference to it could link to that parts of the docs? If so I might knock up a quick Markup page first so I can get the link right

Great idea! Let's do it!

**Comment by bijington** [comment]
- [ ] Add Banner for 'preview' information

**Comment by bijington** [comment]
Current warnings will be resolved by #13

**Review by brminnick — APPROVED** [review]
Thanks @bijington!!

**Pull request merged**
