### PR TITLE
Add an initial landing page for the .NET Community Toolkit

### PR DESCRIPTION
**Pull request by michael-hawker**
FYI @Sergio0694 for review.

Adds info together from the Read me of the .NET Community Toolkit repo to form an initial landing page in this new repo here so we can have a better experience with our new landing page for docs.

I added new TOC/Index.yaml stuff as well to better highlight and branch out to our existing docs for the .NET and WCT.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@michael-hawker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@michael-hawker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Review by Sergio0694 — APPROVED** [review]
:shipit:

**Comment by PRMerger8** [comment]
@michael-hawker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
