### PR TITLE
ColorToComponentConverters

### PR DESCRIPTION
**Pull request by bijington**
Documentation added for .NET MAUI Community Toolkit proposals:

- [Proposal] `ColorToComponentConverters ` <https://github.com/CommunityToolkit/Maui/issues/53>

### CODE REVIEW

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger5** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Review by jfversluis — CHANGES_REQUESTED** [review]
I think something is being copied over and over again because I see the same (wrong) code indentation all the time :D 

See: https://github.com/MicrosoftDocs/CommunityToolkit/pull/69/commits/05873611dbb078ba86e2df6030b84942d76cf7f3

**Comment by bijington** [comment]
> I think something is being copied over and over again because I see the same (wrong) code indentation all the time :D
> 
> See: [0587361](https://github.com/MicrosoftDocs/CommunityToolkit/commit/05873611dbb078ba86e2df6030b84942d76cf7f3)

hmm I see it too on GitHub, perhaps my VS code is applying tabs instead of spaces?

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by bijington** [comment]
@jfversluis based on our earlier chat does anything need to be actioned on this PR? How does the preview look?

**Review by jfversluis — APPROVED** [review]
In light of our chat, this seems all good! Let's gooooo 🚂

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

**Pull request merged**
