### PR TITLE
WCT documentation update v8.1.240328-rc

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR updates the Windows Community Toolkit documentation to align with the 8.1.240328-rc prerelease.

Documentation and ToC was generated by our `./tooling/Build-Toolkit-Docs.ps1` build script, detailed [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/177). 

The `index.md` and `getting-started.md`, which are not present in the generated docs, were manually re-added to the ToC, as well as the links at the bottom.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
@microsoft-github-policy-service agree

**Comment by michael-hawker** [comment]
Thanks Arlo, not sure why we're not seeing the doc build run to give us a preview...

We also need the map of the moved docs, so we can get redirects in place.

**Comment by JasonWHowell** [comment]
@michael-hawker click here and then you can see the build previews:

image

image

In the build log there are View links for each changed file.
For example:  https://review.learn.microsoft.com/en-us/dotnet/communitytoolkit/windows/colorpicker/index?branch=pr-en-us-393

**Comment by michael-hawker** [comment]
Thanks @JasonWHowell for the info, I see that now. I wasn't part of the discussion when the flag to bubble it up with the bot was turned off here: https://github.com/MicrosoftDocs/CommunityToolkit/commit/51d7ca459ae49a13c2bbad870229ee3a6d806032 - so I'm following up with our co-owners of the repo.

The bot post certainly made it clearer when there were warnings and things we should be fixing before committing. FYI @jfversluis, started a thread on teams with the team. 😊

**Comment by Arlodotexe** [comment]
Example of redirects can be found [here](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/blob/main/.openpublishing.redirection.json)

**Comment by jfversluis** [comment]
Voila, careful what you wish for... A lot of warnings to fix 😜

**Comment by Arlodotexe** [comment]
I've added the redirects and followed the existing formatting, not sure why the warnings are still showing there.

**Comment by Arlodotexe** [comment]
Issue persists

**Comment by michael-hawker** [comment]
Awesome, thanks @arlodotexe! I believe everything in main goes live pretty quick, so we should wait to merge this until we're ready to release, right?

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
