### PR TITLE
Toast notifications need additional setup for unpackaged WinUI 3

### PR DESCRIPTION
**Pull request by TheVeryStarlk**
The [docs](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=android) on the toast usage do not mention any setup for WinUI 3. Calling `Toast.Show()` on an unpackaged WinUI 3 application (in MAUI) throws IOE:
```
System.Runtime.InteropServices.COMException: 'Element not found.

Element not found.
'
```

### CODE REVIEW

**Comment by bijington** [comment]
@TheVeryStarlk thank you for the submission. I would prefer that we duplicate the information on both pages rather than linking to another section on another page. We can avoid duplicating the text through an include file.

Would you feel happy to proceed with that change? If not I would be happy to do so/help

**Comment by TheVeryStarlk** [comment]
Hi, good idea! I don't really know how include files work with markdown files. 🤔
I thought I'd just copy & paste the contents.

**Comment by bijington** [comment]
Apologies for the delay, I have made the change to show how to have a shared include file. Let me know what you think

**Comment by jfversluis** [comment]
> @TheVeryStarlk please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@TheVeryStarlk you'll still have to do this before we can merge this, thanks!

**Comment by TheVeryStarlk** [comment]
> @TheVeryStarlk please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by TheVeryStarlk** [comment]
@microsoft-github-policy-service agree

**Comment by jfversluis** [comment]
Thank you @TheVeryStarlk !

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
