### PR TITLE
Update MediaElement.md fix demo bug:  

### PR DESCRIPTION
**Pull request by callmejea**
fix demo bug:  Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:MediaElementState".

### CODE REVIEW

**Comment by jfversluis** [comment]
Hello there, thanks for this PR! I don't think this should be necessary though. Did you see any errors while trying this sample?

**Comment by callmejea** [comment]
only this:

**Comment by callmejea** [comment]
More info : 
Mac M1 pro  13.3.1
visurlStudio : 17.5.5 (build 2)
MediaElement: installed 1.0.2
xml header added:   xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
.net version :7.0;

**Comment by jfversluis** [comment]
Seems this is all resolved then. Thank you!

**Pull request closed without merging**
