### PR TITLE
Initial Maui.Markup overview

### PR DESCRIPTION
**Pull request by bijington**
Adding an overview of the CommunityToolkit.Maui.Markup package ready for the rest of the content to follow.

This PR is based off the content at: https://docs.microsoft.com/en-gb/xamarin/community-toolkit/markup with the following differences:

- Migrate from Xamarin.Forms to Maui details.
- Only focus on an overview allowing us to dive in to more specific topics (e.g. Data binding, etc.) in separate pages

### CODE REVIEW

**Comment by bijington** [comment]
@davidbritch I noticed that we could include the following on the Xamarin Community Toolkit documentation pages:

```markdown
xref:Xamarin.Forms.Grid
```

I tried similar on this PR but for the .NET MAUI specific parts

e.g.

```markdown
xref:Microsoft.Maui.Controls.Grid
```

 but I have seen this issue:

> Line 22, Column 63: [Warning: xref-not-found] Cross reference not found: 'Microsoft.Maui.Controls.Grid'.

Is this something we need to configure on this repo?

**Comment by bijington** [comment]
- [ ] Add Banner for 'preview' information

**Comment by davidbritch** [comment]
You can't do any xref's to Microsoft.Maui.* right now. For them to work it requires API docs for MAUI to have been published. While that's being worked on there's no ETA for when they'll land.

**Comment by bijington** [comment]
> You can't do any xref's to Microsoft.Maui.* right now. For them to work it requires API docs for MAUI to have been published. While that's being worked on there's no ETA for when they'll land.

OK thanks for the answer. I will remove this for now. Do you think it is worth adding back in once it is available? If so I can open an issue so that we remember

**Comment by davidbritch** [comment]
> Do you think it is worth adding back in once it is available? If so I can open an issue so that we remember

Yes. Similarly, there are no API doc links from the MAUI docs but I'll have to add them in once they become available.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by bijington** [comment]
Added an note issue #15 to help remind us

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger3** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by brminnick** [comment]
Thanks Shaun!

> I noticed we supplied a [Recommended conventions](https://docs.microsoft.com/en-gb/xamarin/community-toolkit/markup#recommended-convention) section, is that something this overview page should follow or is this layout fine for now? My reasoning for the current layout is that I believe it makes it easier for a reader to compare the differences between the approaches.

For the .NET MAUI C# Markup docs, let's tweak those recommendations a bit to better follow standard C# nomenclature. The XCT C# Markup docs were written by [Vincent Hoogendoorn](https://github.com/VincentH-Net/CSharpForMarkup) who adds his own flair + style to code formatting which can be a bit jarring to C# devswho are  unfamiliar with that style.

Here's a few things that stick out to me:
- Use empty constructor initializer instead of empty property initializer
  - Change `new Label { }`  to `new Label()`
- Remove the extra space in between method names and their parenthesis
  -  Change `.Row (BodyRow.Message)` to `.Row(BodyRow.Message)`
- Remove the space in between fluent methods
  - Change `.Row(BodyRow.Message) .ColumnSpan(All<BodyCol>())` to `.Row(BodyRow.Message).ColumnSpan(All<BodyCol>())`

Nothing Vincent has written in the XCT C# Markup is incorrect (heck, Miguel de Icaza puts a space in-between his method name and its open parenthesis), but I don't want to scare away anyone.

```cs
new Label { }
    .Assign (out animatedMessageLabel) // purpose
    .Invoke (label => label.SizeChanged += MessageLabel_SizeChanged) // other
    .Row (BodyRow.Message) .ColumnSpan (All<BodyCol>()) // layout
    .Bind (nameof(vm.Message)), // bind default
```

```cs
new Label()
    .Assign(out animatedMessageLabel) // purpose
    .Invoke(label => label.SizeChanged += MessageLabel_SizeChanged) // other
    .Row(BodyRow.Message).ColumnSpan(All<BodyCol>()) // layout
    .Bind(nameof(vm.Message)), // bind default
```

**Comment by brminnick** [comment]
I'm also wondering how we should structure the .NET MAUI Community Toolkit Docs.

Since we technically have 3 .NET MAUI Community Toolkit Libraries that all will have subsections underneath them, I wonder if we should have a `.NET MAUI Community Toolkits` landing page (similar to the `.NET Community Toolkits` landing page) that highlights the 3 libraries? 

Maybe something like this for the folder structure?

```
.NET Community Toolkits 
│   .NET Community Toolkits 
│   Toolkits
└─── .NET Community Toolkit
└─── Windows Community Toolkit
└─── .NET MAUI Community Toolkits
|     └─── CommunityToolkit.Maui
|     └─── CommunityToolkit.Maui.Core
|     └─── CommunityToolkit.Maui.Markup
```

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Review by brminnick — CHANGES_REQUESTED** [review]
Thanks Shaun! 

Let's add these to the table of contents.

I also threw an idea around structuring the folder structure / TOC here: https://github.com/MicrosoftDocs/CommunityToolkit/pull/13#issuecomment-1039591576

I'm not sure that this recommendation is necessarily the best way to do it, but I think it'll be good for us to figure out the structure now so that we don't have to re-architect anything later!

Screen Shot 2022-02-14 at 1 45 48 PM

**Comment by bijington** [comment]
> I'm also wondering how we should structure the .NET MAUI Community Toolkit Docs.
> 
> Since we technically have 3 .NET MAUI Community Toolkit Libraries that all will have subsections underneath them, I wonder if we should have a `.NET MAUI Community Toolkits` landing page (similar to the `.NET Community Toolkits` landing page) that highlights the 3 libraries?
> 
> Maybe something like this for the folder structure?
> 
> ```
> .NET Community Toolkits 
> │   .NET Community Toolkits 
> │   Toolkits
> └─── .NET Community Toolkit
> └─── Windows Community Toolkit
> └─── .NET MAUI Community Toolkits
> |     └─── CommunityToolkit.Maui
> |     └─── CommunityToolkit.Maui.Core
> |     └─── CommunityToolkit.Maui.Markup
> ```

I wasn't sure on this. I originally thought that most of what we could put in to `CommunityToolkit.Maui.Core` would mostly just match an API documentation. Do you think we could fill much content for `.Core`?

I guess explaining the structure would make sense in case anyone wanted to provide their own `.Comet` or similar as we have discussed.

**Comment by bijington** [comment]
> I'm not sure that this recommendation is necessarily the best way to do it, but I think it'll be good for us to figure out the structure now so that we don't have to re-architect anything later!

Perhaps this would be a good topic of discussion with @davidbritch

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by davidbritch** [comment]
I'm not convinced by:

```
└─── .NET MAUI Community Toolkits
|     └─── CommunityToolkit.Maui
|     └─── CommunityToolkit.Maui.Core
|     └─── CommunityToolkit.Maui.Markup
```

That's more of an API docs structure. For conceptual docs it should be broken down into whatever categories you think users will be looking for info on. For example, I doubt users will think "I wonder what I can do with CommunityToolkit.Maui" vs. "I wonder what I can do with CommunityToolkit.Maui.Core.". When they first come to the docs they won't be aware of what the namespaces are.

So it maybe that some kind of structure like the following is better:

```
Get started
Controls
   Customize controls
        Behaviors
        Effects
X, Y, Z (whatever X,Y,Z is)
etc.
```

Really it's about providing a structure that will make sense to users the first time they visit the docs.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by bijington** [comment]
@brminnick would you mind checking if the preview now looks right? Sorry I wish I could check and help out there

**Review by brminnick — APPROVED** [review]
Thanks @bijington!

I tweaked the TOC just a bit to avoid the duplicate `Markup`

**Pull request merged**
