### PR TITLE
Item tapped event args converter

### PR DESCRIPTION
**Pull request by CliffAgius**
Added the docs for the ItemTappedEventArgsConverter however I have not used C# MarkUp and I am a little lost on the best way to document this part.
Be grateful for any help on this section and hopefully I can learn how it works for other Docs files, I have searched about and there is very little Docs/Blogs/Tutorials on the Markup extention.

    - [Proposal] ItemTappedEventArgs Converter #68

### CODE REVIEW

**Comment by bijington** [comment]
> Added the docs for the ItemTappedEventArgsConverter however I have not used C# MarkUp and I am a little lost on the best way to document this part. Be grateful for any help on this section and hopefully I can learn how it works for other Docs files, I have searched about and there is very little Docs/Blogs/Tutorials on the Markup extention.
> 
> ```
> - [Proposal] ItemTappedEventArgs Converter #68
> ```

@CliffAgius thanks for this PR. To possibly help while we don't have too much documentation on this yet we have a brief overview of Markup here: https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/markup/markup.md I guess we may need to improve on this. We will eventually have a set of further documentation covering each of the functionality that is possible but for now the best example of needing to achieve what you need is likely to look at this behaviours page: https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/behaviors/maximum-length-reached-behavior.md along with any existing converters page. The markup package should reduce the amount of code required to set up bindings, etc. through the use of extension methods. I guessing knowing those will be challenging without the docs for them.

**Comment by bijington** [comment]
Let me know if I can help in any way

**Comment by jfversluis** [comment]
@CliffAgius just checking you're going to do more work on this first or you want me to review?

**Comment by CliffAgius** [comment]
Will be getting back to this one and others this week currently away with the family on a holiday. 😁

**Comment by jfversluis** [comment]
@CliffAgius is this PR supposed to look this way? 😅

**Comment by CliffAgius** [comment]
Hey team, Yes sorry I tried to push but the number of changes caused a lot of merge conflicts as the orders of the Index and TOC files had been changed.

I can close this PR and start a fresh PR with just my changes again over the latest main if that is better?  This is what I did with the last PR I sent in but I noticed it caused the removal of the comments around the PR which is history and I didn't think that was right either.

Open to suggestions as I guess I am not doing this part right.

**Comment by bijington** [comment]
> Hey team, Yes sorry I tried to push but the number of changes caused a lot of merge conflicts as the orders of the Index and TOC files had been changed.
> 
> 
> 
> I can close this PR and start a fresh PR with just my changes again over the latest main if that is better?  This is what I did with the last PR I sent in but I noticed it caused the removal of the comments around the PR which is history and I didn't think that was right either.
> 
> 
> 
> Open to suggestions as I guess I am not doing this part right.

I believe you are seeing all of these changes because we squash merge our PRs and therefore the commit history is lost. I would suggest to go with whatever is easiest for you but the 2 options are:

- open a new PR off a clean branch
- perform a rebase of your current branch against `main` @jfversluis has a good blog post on how to do it but I can't find it right now

**Comment by jfversluis** [comment]
The blog post is here if you want to try it: https://blog.verslu.is/git/git-rebase/

But a new PR works just as well, which ever you prefer :)

**Pull request closed without merging**
